export  const CartActionTypes = {
    TOGGLE_CART_HIDDEN : 'TOGGLE_CART_HIDDEN',
    ADD_ITEM: 'ADD_ITEM',
    REMOVE_ITEM: 'REMOVE_ITEM',
    REMOVE_ITEM_FROM_CART: 'REMOVE_ITEM_FROM_CART',
    CLEAR_ALL_ITEMS_FROM_CART_START: 'CLEAR_ALL_ITEMS_FROM_CART_START',
    CLEAR_ALL_ITEMS_FROM_CART: 'CLEAR_ALL_ITEMS_FROM_CART',
}